steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-app']

# Step to run tests using Gemini 1.0
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud ai custom-jobs create \
      --region=us-central1 \
      --display-name="Run Tests with Gemini 1.0" \
      --python-package-uris=gs://your-bucket/path/to/your/test-script.tar.gz \
      --script=path/to/gemini1_0_test_script.py \
      --args="gcr.io/$PROJECT_ID/my-app"

# Step to run tests using Gemini 1.5
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud ai custom-jobs create \
      --region=us-central1 \
      --display-name="Run Tests with Gemini 1.5" \
      --python-package-uris=gs://your-bucket/path/to/your/test-script.tar.gz \
      --script=path/to/gemini1_5_test_script.py \
      --args="gcr.io/$PROJECT_ID/my-app"

# Deployment step, only runs if the tests pass
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud run deploy my-app \
    --image gcr.io/$PROJECT_ID/my-app \
    --platform managed \
    --region us-central1

timeout: 1200s
