steps:
  # Build the container image for the main app
  - name: 'gcr.io/cloud-builders/docker'
    id: BuildApp
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/ankercloud-testing-account/genai/flask-login-app1:latest'
      - '.'

  # Push the container image for the main app
  - name: 'gcr.io/cloud-builders/docker'
    id: PushApp
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/ankercloud-testing-account/genai/flask-login-app1:latest'

  # Create a custom job to run tests with Gemini 1.0
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud ai custom-jobs create \
          --region=asia-south1 \
          --display-name="Run Tests with Gemini 1.0" \
          --worker-pool-spec='[{"machineSpec":{"machineType":"n1-standard-4"},"replicaCount":1,"containerSpec":{"imageUri":"asia-south1-docker.pkg.dev/ankercloud-testing-account/genai/flask-login-app1:latest","args":["python","gemini1_0_test_script.py","https://github.com/vebss123/GENAI-Devops.git"]}}]'

  # Deploy the application to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy my-app \
          --image gcr.io/ankercloud-testing-account/my-app \
          --platform managed \
          --region asia-south1
