steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ACT-MS-Testing/my-app', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ACT-MS-Testing/my-app']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud ai custom-jobs create \
      --region=asia-south-1 \
      --display-name="Run Tests with Gemini 1.0" \
      --python-package-uris=gs://gen-ai-devops/test-script.tar \
      --script=gemini1_0_test_script.py \
      --args="https://github.com/vebss123/GENAI-Devops.git"

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud run deploy my-app \
    --image gcr.io/ACT-MS-Testing/my-app \
    --platform managed \
    --region asia-south-1
