steps:
- id: "Build Docker Image"
  name: 'gcr.io/cloud-builders/docker:latest'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/ankercloud-testing-account/gen-ai-poc/ai-poc', '.']

- id: "Push Docker Image To Artifact Registry"
  name: 'gcr.io/cloud-builders/docker:latest'
  args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/ankercloud-testing-account/gen-ai-poc/ai-poc']

- id: "Deploy Cloud Run Service"
  name: 'gcr.io/cloud-builders/gcloud:latest'
  args: [
    'run', 'deploy', 'gen-ai', 
    '--service-account', '263666966446-compute@developer.gserviceaccount.com',
    '--allow-unauthenticated',
    '--memory', '1024Mi',
    '--platform', 'managed',
    '--image', 'us-central1-docker.pkg.dev/ankercloud-testing-account/gen-ai-poc/ai-poc:latest',
    '--timeout', '30',
    '--min-instances', '0',
    '--max-instances', '1',
    '--ingress', 'all',
    '--region', 'us-central1'
  ]

timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true
